name: "Pull Request Verifier"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main
concurrency:
  group: ${{ github.repository }}-pull-request-verifier-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Verify"
        run: |
          # Bash script
          .scripts/verify.sh
